#!/usr/bin/env python3
"""Generate Construction Budget Dashboard Excel file."""
import openpyxl
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side, numbers
from openpyxl.chart import BarChart, PieChart, Reference
from openpyxl.formatting.rule import CellIsRule
from openpyxl.utils import get_column_letter
import os

OUTPUT = os.environ.get("OUTPUT_DIR", ".") + "/construction-budget-dashboard.xlsx"

# Style constants
HEADER_FONT = Font(name="Arial", bold=True, color="FFFFFF", size=11)
HEADER_FILL = PatternFill(start_color="2F5496", end_color="2F5496", fill_type="solid")
SUBHEADER_FONT = Font(name="Arial", bold=True, size=10)
SUBHEADER_FILL = PatternFill(start_color="D6E4F0", end_color="D6E4F0", fill_type="solid")
BODY_FONT = Font(name="Arial", size=10)
CURRENCY_FMT = '#,##0'
PERCENT_FMT = '0%'
THIN_BORDER = Border(
    left=Side(style="thin"), right=Side(style="thin"),
    top=Side(style="thin"), bottom=Side(style="thin")
)
GREEN_FILL = PatternFill(start_color="C6EFCE", end_color="C6EFCE", fill_type="solid")
RED_FILL = PatternFill(start_color="FFC7CE", end_color="FFC7CE", fill_type="solid")


def apply_style(ws, row, col, font=BODY_FONT, fill=None, fmt=None, alignment=None):
    cell = ws.cell(row=row, column=col)
    cell.font = font
    cell.border = THIN_BORDER
    if fill:
        cell.fill = fill
    if fmt:
        cell.number_format = fmt
    if alignment:
        cell.alignment = alignment
    return cell


def create_dashboard(wb):
    ws = wb.active
    ws.title = "Dashboard"
    ws.sheet_properties.tabColor = "2F5496"

    # Title
    ws.merge_cells("A1:G1")
    title_cell = ws["A1"]
    title_cell.value = "CONSTRUCTION PROJECT BUDGET DASHBOARD"
    title_cell.font = Font(name="Arial", bold=True, size=16, color="2F5496")
    title_cell.alignment = Alignment(horizontal="center")
    ws.row_dimensions[1].height = 35

    ws.merge_cells("A2:G2")
    ws["A2"].value = "Generated by Flowtech Advisory | Update figures monthly"
    ws["A2"].font = Font(name="Arial", italic=True, size=9, color="808080")
    ws["A2"].alignment = Alignment(horizontal="center")

    # Headers row 4
    headers = ["Project Name", "Budget ($)", "Actual ($)", "Variance ($)", "Variance %", "% Complete", "Status"]
    for col, h in enumerate(headers, 1):
        c = apply_style(ws, 4, col, HEADER_FONT, HEADER_FILL)
        c.value = h
        c.alignment = Alignment(horizontal="center")

    # Sample data
    projects = [
        ("Riverside Tower - Stage 1", 4500000, 4200000, 0.85),
        ("Metro Station Upgrade", 12000000, 13500000, 0.62),
        ("Harbour Bridge Maintenance", 2800000, 2650000, 0.95),
        ("CBD Office Fit-out L12", 1200000, 1180000, 0.78),
        ("Westfield Expansion Wing C", 8500000, 7900000, 0.45),
    ]

    for i, (name, budget, actual, pct) in enumerate(projects):
        row = 5 + i
        apply_style(ws, row, 1).value = name
        apply_style(ws, row, 2, fmt=CURRENCY_FMT).value = budget
        apply_style(ws, row, 3, fmt=CURRENCY_FMT).value = actual
        # Variance formula
        apply_style(ws, row, 4, fmt=CURRENCY_FMT).value = f"=B{row}-C{row}"
        # Variance % formula
        apply_style(ws, row, 5, fmt=PERCENT_FMT).value = f"=IF(B{row}=0,0,D{row}/B{row})"
        apply_style(ws, row, 6, fmt=PERCENT_FMT).value = pct
        # Status formula
        apply_style(ws, row, 7).value = f'=IF(D{row}>=0,"Under Budget","Over Budget")'

    # Totals row
    total_row = 10
    apply_style(ws, total_row, 1, SUBHEADER_FONT, SUBHEADER_FILL).value = "TOTAL"
    for col in [2, 3, 4]:
        c = apply_style(ws, total_row, col, SUBHEADER_FONT, SUBHEADER_FILL, CURRENCY_FMT)
        col_letter = get_column_letter(col)
        c.value = f"=SUM({col_letter}5:{col_letter}9)"
    apply_style(ws, total_row, 5, SUBHEADER_FONT, SUBHEADER_FILL, PERCENT_FMT).value = f"=IF(B{total_row}=0,0,D{total_row}/B{total_row})"
    apply_style(ws, total_row, 6, SUBHEADER_FONT, SUBHEADER_FILL, PERCENT_FMT).value = f"=AVERAGE(F5:F9)"
    apply_style(ws, total_row, 7, SUBHEADER_FONT, SUBHEADER_FILL).value = ""

    # Conditional formatting on variance column
    ws.conditional_formatting.add("D5:D9", CellIsRule(
        operator="greaterThanOrEqual", formula=["0"], fill=GREEN_FILL
    ))
    ws.conditional_formatting.add("D5:D9", CellIsRule(
        operator="lessThan", formula=["0"], fill=RED_FILL
    ))

    # Column widths
    widths = [30, 16, 16, 16, 14, 14, 16]
    for i, w in enumerate(widths):
        ws.column_dimensions[get_column_letter(i + 1)].width = w

    # Bar chart: Budget vs Actual
    chart = BarChart()
    chart.type = "col"
    chart.title = "Budget vs Actual by Project"
    chart.y_axis.title = "Amount ($)"
    chart.x_axis.title = "Project"
    chart.style = 10
    chart.width = 22
    chart.height = 14

    cats = Reference(ws, min_col=1, min_row=5, max_row=9)
    budget_data = Reference(ws, min_col=2, min_row=4, max_row=9)
    actual_data = Reference(ws, min_col=3, min_row=4, max_row=9)
    chart.add_data(budget_data, titles_from_data=True)
    chart.add_data(actual_data, titles_from_data=True)
    chart.set_categories(cats)
    chart.series[0].graphicalProperties.solidFill = "2F5496"
    chart.series[1].graphicalProperties.solidFill = "F97316"
    ws.add_chart(chart, "A12")

    # Pie chart: Completion status
    pie = PieChart()
    pie.title = "Project Completion Status"
    pie.style = 10
    pie.width = 14
    pie.height = 14
    pie_data = Reference(ws, min_col=6, min_row=4, max_row=9)
    pie_cats = Reference(ws, min_col=1, min_row=5, max_row=9)
    pie.add_data(pie_data, titles_from_data=True)
    pie.set_categories(pie_cats)
    ws.add_chart(pie, "E12")


def create_cost_breakdown(wb):
    ws = wb.create_sheet("Cost Breakdown")
    ws.sheet_properties.tabColor = "F97316"

    ws.merge_cells("A1:N1")
    ws["A1"].value = "COST BREAKDOWN BY CATEGORY"
    ws["A1"].font = Font(name="Arial", bold=True, size=14, color="2F5496")
    ws["A1"].alignment = Alignment(horizontal="center")

    # Headers
    months = ["Jan", "Feb", "Mar", "Apr", "May", "Jun",
              "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"]
    apply_style(ws, 3, 1, HEADER_FONT, HEADER_FILL).value = "Category"
    for i, m in enumerate(months):
        apply_style(ws, 3, i + 2, HEADER_FONT, HEADER_FILL).value = m
        apply_style(ws, 3, i + 2).alignment = Alignment(horizontal="center")
    apply_style(ws, 3, 14, HEADER_FONT, HEADER_FILL).value = "Total"

    # Budget section
    categories_budget = {
        "Labour": [380000, 395000, 410000, 420000, 415000, 400000, 390000, 410000, 425000, 430000, 420000, 380000],
        "Materials": [250000, 280000, 320000, 350000, 340000, 310000, 290000, 330000, 360000, 340000, 300000, 260000],
        "Equipment": [120000, 125000, 130000, 135000, 130000, 125000, 120000, 130000, 135000, 130000, 125000, 120000],
        "Subcontractors": [450000, 480000, 520000, 550000, 540000, 500000, 470000, 530000, 560000, 540000, 490000, 440000],
        "Overheads": [85000, 85000, 90000, 90000, 90000, 85000, 85000, 90000, 90000, 90000, 85000, 85000],
        "Contingency": [50000, 50000, 55000, 55000, 55000, 50000, 50000, 55000, 55000, 55000, 50000, 50000],
    }

    ws.merge_cells("A4:N4")
    apply_style(ws, 4, 1, SUBHEADER_FONT, SUBHEADER_FILL).value = "BUDGET"
    for i in range(2, 15):
        apply_style(ws, 4, i, fill=SUBHEADER_FILL)

    row = 5
    for cat, values in categories_budget.items():
        apply_style(ws, row, 1).value = cat
        for j, v in enumerate(values):
            apply_style(ws, row, j + 2, fmt=CURRENCY_FMT).value = v
        col_letter_start = get_column_letter(2)
        col_letter_end = get_column_letter(13)
        apply_style(ws, row, 14, SUBHEADER_FONT, fmt=CURRENCY_FMT).value = f"=SUM({col_letter_start}{row}:{col_letter_end}{row})"
        row += 1

    # Budget totals
    apply_style(ws, row, 1, SUBHEADER_FONT, SUBHEADER_FILL).value = "BUDGET TOTAL"
    for col in range(2, 15):
        cl = get_column_letter(col)
        apply_style(ws, row, col, SUBHEADER_FONT, SUBHEADER_FILL, CURRENCY_FMT).value = f"=SUM({cl}5:{cl}{row - 1})"
    budget_total_row = row

    # Actual section
    row += 2
    ws.merge_cells(f"A{row}:N{row}")
    apply_style(ws, row, 1, SUBHEADER_FONT, SUBHEADER_FILL).value = "ACTUAL"
    for i in range(2, 15):
        apply_style(ws, row, i, fill=SUBHEADER_FILL)

    row += 1
    actual_start = row
    categories_actual = {
        "Labour": [390000, 405000, 425000, 440000, 430000, 415000, 400000, 0, 0, 0, 0, 0],
        "Materials": [260000, 295000, 340000, 370000, 355000, 325000, 300000, 0, 0, 0, 0, 0],
        "Equipment": [125000, 130000, 140000, 145000, 138000, 132000, 128000, 0, 0, 0, 0, 0],
        "Subcontractors": [460000, 500000, 545000, 580000, 560000, 520000, 490000, 0, 0, 0, 0, 0],
        "Overheads": [88000, 92000, 95000, 93000, 91000, 88000, 87000, 0, 0, 0, 0, 0],
        "Contingency": [15000, 25000, 30000, 40000, 20000, 10000, 5000, 0, 0, 0, 0, 0],
    }

    for cat, values in categories_actual.items():
        apply_style(ws, row, 1).value = cat
        for j, v in enumerate(values):
            apply_style(ws, row, j + 2, fmt=CURRENCY_FMT).value = v
        cl_s = get_column_letter(2)
        cl_e = get_column_letter(13)
        apply_style(ws, row, 14, SUBHEADER_FONT, fmt=CURRENCY_FMT).value = f"=SUM({cl_s}{row}:{cl_e}{row})"
        row += 1

    # Actual totals
    apply_style(ws, row, 1, SUBHEADER_FONT, SUBHEADER_FILL).value = "ACTUAL TOTAL"
    for col in range(2, 15):
        cl = get_column_letter(col)
        apply_style(ws, row, col, SUBHEADER_FONT, SUBHEADER_FILL, CURRENCY_FMT).value = f"=SUM({cl}{actual_start}:{cl}{row - 1})"
    actual_total_row = row

    # Variance section
    row += 2
    ws.merge_cells(f"A{row}:N{row}")
    apply_style(ws, row, 1, SUBHEADER_FONT, SUBHEADER_FILL).value = "VARIANCE (Budget - Actual)"
    for i in range(2, 15):
        apply_style(ws, row, i, fill=SUBHEADER_FILL)
    row += 1

    apply_style(ws, row, 1, SUBHEADER_FONT).value = "VARIANCE"
    for col in range(2, 15):
        cl = get_column_letter(col)
        c = apply_style(ws, row, col, SUBHEADER_FONT, fmt=CURRENCY_FMT)
        c.value = f"={cl}{budget_total_row}-{cl}{actual_total_row}"

    # Conditional formatting on variance row
    var_range = f"B{row}:N{row}"
    ws.conditional_formatting.add(var_range, CellIsRule(operator="greaterThanOrEqual", formula=["0"], fill=GREEN_FILL))
    ws.conditional_formatting.add(var_range, CellIsRule(operator="lessThan", formula=["0"], fill=RED_FILL))

    # Column widths
    ws.column_dimensions["A"].width = 18
    for i in range(2, 15):
        ws.column_dimensions[get_column_letter(i)].width = 14


def create_instructions(wb):
    ws = wb.create_sheet("Instructions")
    ws.sheet_properties.tabColor = "70AD47"

    instructions = [
        ("CONSTRUCTION BUDGET DASHBOARD - INSTRUCTIONS", True, 16),
        ("", False, 10),
        ("How to Use This Dashboard", True, 13),
        ("", False, 10),
        ("1. Dashboard Tab", True, 11),
        ("   - Enter your project names in column A (rows 5-9)", False, 10),
        ("   - Enter the total budget for each project in column B", False, 10),
        ("   - Enter the actual spend to date in column C", False, 10),
        ("   - Variance and Status columns calculate automatically", False, 10),
        ("   - Update the % Complete column manually each month", False, 10),
        ("   - Charts update automatically when data changes", False, 10),
        ("", False, 10),
        ("2. Cost Breakdown Tab", True, 11),
        ("   - Budget section: Enter your planned monthly spend per category", False, 10),
        ("   - Actual section: Enter actual monthly spend as invoices are processed", False, 10),
        ("   - Variance section calculates automatically", False, 10),
        ("   - Green = under budget, Red = over budget", False, 10),
        ("", False, 10),
        ("3. Adding More Projects", True, 11),
        ("   - Insert rows above the TOTAL row on the Dashboard tab", False, 10),
        ("   - Copy formulas from an existing row", False, 10),
        ("   - Update the chart data range to include new rows", False, 10),
        ("", False, 10),
        ("4. Formula Reference", True, 11),
        ("   - Variance = Budget - Actual", False, 10),
        ("   - Variance % = Variance / Budget", False, 10),
        ("   - Status = IF(Variance >= 0, \"Under Budget\", \"Over Budget\")", False, 10),
        ("   - All totals use SUM formulas", False, 10),
        ("", False, 10),
        ("5. Tips", True, 11),
        ("   - Print the Dashboard tab for monthly project meetings", False, 10),
        ("   - Use the Cost Breakdown for detailed financial reviews", False, 10),
        ("   - Back up this file monthly before making changes", False, 10),
        ("   - Protect sheets (Review > Protect Sheet) to prevent accidental edits", False, 10),
    ]

    for i, (text, bold, size) in enumerate(instructions, 1):
        cell = ws.cell(row=i, column=1, value=text)
        cell.font = Font(name="Arial", bold=bold, size=size,
                         color="2F5496" if bold and size > 11 else "000000")

    ws.column_dimensions["A"].width = 80


def main():
    wb = openpyxl.Workbook()
    create_dashboard(wb)
    create_cost_breakdown(wb)
    create_instructions(wb)
    os.makedirs(os.path.dirname(OUTPUT), exist_ok=True)
    wb.save(OUTPUT)
    print(f"Created: {OUTPUT}")


if __name__ == "__main__":
    main()
